### ISSUE TITLE
apt command error

### ISSUE THREAD

**Issue by MaiLunJiye** [NeoTerrm/NeoTerm#14]
$ apt
CANNOT LINK EXECUTABLE "apt": library "libgnustl_shared.so" not found

environment:
lenovo K920 
lineage 14 
Android 7.1.2

**Comment by ghost** [comment]
Okay! There is no such problem for me but apt is outdated and needs to be updated! But it's working well try to "apt-get install apt" or reinstall NeoTerm!

**Comment by imkiva** [comment]
Fixed in v2.0.0, check it out [here](https://github.com/NeoTerm/NeoTerm/releases/tag/v2.0.0)
