### ISSUE TITLE
Add Support for boot.img-tools

### ISSUE THREAD

**Issue by ghost** [NeoTerrm/NeoTerm#15]
https://mega.nz/#!tjJWQKYL!pIvXh3b0wHPc0KEt-10LbOT9pvuRirWbODoCish1K4g
Or
https://drive.google.com/file/d/1hfV_wQTNmr0jQtMyNYBDhA2WxyiXdXq1/view?usp=drivesdk

**Comment by imkiva** [comment]
Nice job!

**Comment by ghost** [comment]
@zt515 thanks baby!

**Comment by ghost** [comment]
Telegram?
