### ISSUE TITLE
libgnustl_shared.so not found

### ISSUE THREAD

**Issue by OhYee** [NeoTerrm/NeoTerm#16]
version: 1.2.10-d67d9da
system: android 7.0

**Comment by ghost** [comment]
@OhYee can you explain when you getting this error?

**Comment by OhYee** [comment]
can not get in the app
"java.net.SocketTimeoutException: timeout"

or get in the app but can not install software, and warning ".... libgnustl_shared.so not found ..."
(after updating my phone to android N, it can not work on my phone)

**Comment by kotomei** [comment]
You can try to install `apt` manually by `dpkg`

**Comment by vaginessa** [comment]
Same on GT-I9505 (jfltexx) running AICP 5.1.1, NeoTerm 1.2.10-d67d9da right after the first run...![Screenshot](https://framapic.org/ZUQhGg4pkxXO/ePV1A2zav2bd.png)

**Comment by Ublimjo** [comment]
Full error message
![screenshot_2018-02-01-14-22-01](https://user-images.githubusercontent.com/17401813/35676085-847c9c3e-075b-11e8-9063-d5b3b2ac5f1e.jpg)

**Comment by imkiva** [comment]
Fixed in v2.0.0, check it out [here](https://github.com/NeoTerm/NeoTerm/releases/tag/v2.0.0)

**Comment by Ublimjo** [comment]
![screenshot_2018-02-08-12-34-17](https://user-images.githubusercontent.com/17401813/35965734-db7a231e-0ccc-11e8-8815-6e6ed62ba592.jpg)
