### ISSUE TITLE
Where can the APK be found?

### ISSUE THREAD

**Issue by IzzySoft** [NeoTerrm/NeoTerm#3]
As an end-user, I miss some information on where to obtain the app to give it a try. So would you consider e.g. providing one here at Github (best place: see [Creating Releases](https://help.github.com/articles/creating-releases/) in the Github help)? Or would you mind asking F-Droid to build and distribute (I could help you with that then)?

**Comment by imkiva** [comment]
@IzzySoft Sorry about that, I was too busy with both of study and development. I will provide the pre
built APKs on GitHub later. But now you can download the apk from [CoolApk](https://www.coolapk.com/apk/io.neoterm), whose server is located in China, so it may be a little slow while downloading.

I have been searching for a way to spread NeoTerm. I would like to appreciate it if you could help me. 

_Sent from my Meizu M5 Note using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by IzzySoft** [comment]
Sure I can help with that: as soon as the `.apk` is available here at Github, I can add it to [my F-Droid repo](https://apt.izzysoft.de/fdroid/), where new versions then would be available within ~24h of your publishing them here and folks using the F-Droid client get informed automatically.

Also, as I've said, I could help you bring it to the "official F-Droid repo" if you want. They would build the `.apk` themselves from your code, and have it signed with their key. Just let me know if I should initiate the required steps.

**Comment by imkiva** [comment]
@IzzySoft Yes, please add it to your F-Droid repo. You can download the prebuilt apk in Release Page. Thanks a lot!

_Sent from my Meizu M5 Note using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by IzzySoft** [comment]
Done: You can find it [here](https://apt.izzysoft.de/fdroid/index/apk/io.neoterm) now. As pointed out above, updates should show up there within 24h after you tagged them and had the `.apk` attached to the tag. Enjoy, and thanks!

PS: The offer for the official repo still stands (and doesn't conflict with what we've achieved now). If you wish to proceed that way and need help, simply "ping" me by updating this issue :wink:
