### ISSUE TITLE
Online Setup failed

### ISSUE THREAD

**Issue by Wolfram-Wolf** [NeoTerrm/NeoTerm#32]
The latest app release (version 2.0.0) comes with http://janyo.pw:82/kiva/neoterm as the online setup url. However, the installation fails with java.net.UnknownHostException.

**Comment by ghost** [comment]
Can you paste installation log at here?

**Comment by Wolfram-Wolf** [comment]
<code>
11-08 08:01:39.518 E/NeoTerm-NeoTerm-Emulator(21639): [Thread:Thread-3], run(null:-1): args[0] = Bootstrap error 
11-08 08:01:39.518 E/NeoTerm-NeoTerm-Emulator(21639): args[1] = java.net.UnknownHostException: Unable to resolve host "janyo.pw": No address associated with hostname</code>

**Comment by ghost** [comment]
You should change your repository URL, or you can build your own NeoTerm repository.

**Comment by imkiva** [comment]
The new release will be released tonight which has fixed this problem.

**Comment by Wolfram-Wolf** [comment]
Version 2.0.3 fixes this problem.
