### ISSUE TITLE
Document installation options

### ISSUE THREAD

**Issue by Wolfram-Wolf** [NeoTerrm/NeoTerm#33]
Please explain the use of the local/assets zip install files at the install prompt. Could you provide the necessary offline install zip files in this repo as currently both neoterm.studio and janyo.pw seem to be down. Thanks!

**Comment by imkiva** [comment]
OK.

**Comment by Wolfram-Wolf** [comment]
Using the bootstrap-arm.zip file from the termux repo and selecting assets zip install method results in "offline_setup/arm.zip file not found". I was going through the installation code (in Kotlin) and it seemed to work exactly as in termux (parse SYMLINKS.TXT to populate /usr-staging). Could you please direct me as to how could I use the termux  installation zip here? Thanks in advance!

**Comment by imkiva** [comment]
New release and offline zips are here: https://github.com/NeoTerm/NeoTerm/releases/tag/v2.0.3

**Comment by Wolfram-Wolf** [comment]
The offline zips work as expected.
