### ISSUE TITLE
请问如果我想把软件主界面背景弄成透明的该怎么做

### ISSUE THREAD

**Issue by 311303** [NeoTerrm/NeoTerm#42]
请问如果我想把软件主界面背景弄成透明的该怎么做，现在设置界面已经是透明的了
![Screenshot_20190422-072919](https://user-images.githubusercontent.com/41131571/56476836-5f846c80-64d0-11e9-8dea-cce3a1d32521.jpg)
![Screenshot_20190422-072925](https://user-images.githubusercontent.com/41131571/56476839-627f5d00-64d0-11e9-860a-5127c14d3418.jpg)

**Comment by imkiva** [comment]
这个暂时做不到，不过下个版本我会加入这样的选项

**Comment by 311303** [comment]
> 这个暂时做不到，不过下个版本我会加入这样的选项

谢了
