### ISSUE TITLE
JDK8

### ISSUE THREAD

**Issue by ashish0304** [NeoTerrm/NeoTerm#43]
Hi,
After installing jdk-8, I'm getting error on execution of java/javac, "Bad system call".
I'm using Nokia 6.1 Plus, stock Android 9 with March 2019 security patch.
Please help.

**Comment by imkiva** [comment]
JDK8 is not compatible with Android 9. Try openjdk-9

**Comment by 311303** [comment]
I downloaded jdk8 on the official website and it can be used, but you need root and gcc, and link ld*. so to / Lib
