### ISSUE TITLE
Can't install it on my jellybean android

### ISSUE THREAD

**Issue by SoumyadeepChatterjee96** [NeoTerrm/NeoTerm#45]
Well, I have an android device running JellyBean 4.1.2 on low end hardware and I wanted to install Neoterm but it says problem parsing package. Can anyone tell me why? Is it the JellyBean or the lack of 64bit arch on the SOC? Can anyone recommend some app if not this to install SSH and Node-Red?

**Comment by GalaxySnail** [comment]
I guess it is because this NeoTerm was a front end of Termux, but Termux requires Andriod 5.0.
