### ISSUE TITLE
openjdk-9的源码在哪里？

### ISSUE THREAD

**Issue by CosineMath** [NeoTerrm/NeoTerm#55]
你好！
我们正在研究如何更好地在android上使用openjdk，得知NeoTerm的软件包中有一份openjdk-9，看上去是使用android特有的工具链编译的，基于原生的bionic libc而非glibc。这对我们意义重大，请你根据GPL的要求提供源代码，谢谢！

**Comment by imkiva** [comment]
需要说明的是，NeoTerm 的绝大部分软件包都来自 Termux，由于国内 GitHub 访问速度问题，fork 过的 termux-packages 位于 gitee：https://gitee.com/imkiva/neo-term-packages

OpenJDK 9 位于 https://gitee.com/imkiva/neo-term-packages/tree/master/disabled-packages/openjdk-9-jre-headless

OpenJDK 官网提供了完整的编译说明，包括但不限于如何获取源码和如何为安卓平台交叉编译。

然后我想纠正你对 GPL 的一些误解：

* 最先，根据 [GNU 官网的 FAQ](https://www.gnu.org/licenses/gpl-faq.en.html#CanIDemandACopy)
> **If I know someone has a copy of a GPL-covered program, can I demand they give me a copy? (#CanIDemandACopy)**
>> No. The GPL gives a person permission to make and redistribute copies of the program if and when that person chooses to do so. That person also has the right not to choose to redistribute the program.

希望你懂我意思 :)

* 其次，NeoTerm 中使用 apt 管理 GPL 软件的二进制包，对 NeoTerm 本身而言不满足 GPL 扩散性的条件。
* 再次，NeoTerm 使用了 Termux 的源代码，所以 NeoTerm 本身以 GPL 开源，这已经符合 GPL 的要求。NeoTerm Packages 仓库源自 termux-package，在 fork 时 termux-package 仓库对其中的编译框架使用的是 Apache License, Version 2.0，并没有扩散性和强制开源要求，希望你懂我意思 :)
* 最后，我并未修改任何 OpenJDK 9 的源代码，我做的只是写了一些编译脚本，根据上两条，这些编译脚本不在 GPL 扩散性的范围内。

**Comment by CosineMath** [comment]
感谢你的回复！我们会去研究这份源码的。非常感谢！

不过，关于GPL，我对此有不同的理解。在这件事中，对我而言，NeoTerm是我获取openjdk-9的一个渠道，或者说，你通过NeoTerm分发了openjdk-9的二进制形式。我向你索要openjdk-9的源码或者询问有效的源码获取途径是完全合理的。GPL规定了你必须在分发二进制程序时同时保障人们获取源码的权利（虽然许多情况下人们并无此需求），除非你对这份软件获得了另外的许可。

所以，通过NeoTerm分发GPL协议的软件的二进制形式时需要同时注意源代码，因为这意味着你需要同时保障人们获取源代码的权利。如果你发现难以保障（无法提供源代码或告诉人们有效的获取源代码的渠道），此时继续分发GPL协议的软件就是不合适的。

**Comment by imkiva** [comment]
谢谢，不过我希望您能学会沟通的方式。

你的要求虽然合理，也符合道德要求，但您的沟通方式让我感到不适。

> 请你根据GPL的要求提供源代码

这句话一般不会出现在第一次沟通中。

**Comment by CosineMath** [comment]
对此我表示十分抱歉，今后我会更加注意措辞，谢谢你的提醒。
