### ISSUE TITLE
【提问】bootstrap怎么做？我做的体积好大

### ISSUE THREAD

**Issue by LinXueyuanStdio** [NeoTerrm/NeoTerm#56]
NeoTerm提供的bootstrap包只有20M，怎么做到的？
我根据 https://github.com/termux/termux-packages 生成apt包都有好几十M。。。

**Comment by imkiva** [comment]
删除一些无用的 man-page、info 文件和 locale 文件就可以大幅度减少体积，具体代码可以看 https://gitee.com/imkiva/neo-term-packages/blob/master/neobuild#L1123
