### ISSUE TITLE
[Feature-Request] Proot-Distro

### ISSUE THREAD

**Issue by ruizlenato** [NeoTerrm/NeoTerm#60]
I use termux because of the proot-distro, which allowed me to use other distros like ArchLinux, I really wanted this feature on NeoTerm

**Comment by Martinvlba** [comment]
Actually am making a neoterm to work with termux-packages that are recompiled for neoterm so proot and proot-distro can be added. But i cant give any ETA when it will be ready.

**Comment by Martinvlba** [comment]
Anyways here's a early look for neoterm with termux-packages (Added proot-distro)

Also gonna close the issue now as proot-distro is added and new release shouldnt take long now.

[app-debug.zip](https://github.com/NeoTerm/NeoTerm/files/6420696/app-debug.zip)
