### ISSUE TITLE
remember to increase versionCode

### ISSUE THREAD

**Issue by IzzySoft** [NeoTerrm/NeoTerm#64]
Please remember to always increase `versionCode` when making a release. Currently, both v2.0.4 and v2.0.5 have the very same `versionCode: 37` and thus are handles by Android as being the same version (i.e. v2.0.5 is not offered as update if you have v2.0.4 installed).

Thanks!

**Comment by Martinvlba** [comment]
Bumped the VersionCode up by 1.
Also sorry for late reply.
https://github.com/NeoTerm/NeoTerm/commit/2dbc16cc68c87ece6d5feb1cb5d89b96b50e1dab

**Comment by IzzySoft** [comment]
Thanks a lot! 2 questions on this:

* as you bumped it for an existing release (2.0.5), was the APK replaced?
* did you make "a knot in your handkerchief" to remember for the next release? :speak_no_evil: :see_no_evil:

**Comment by Martinvlba** [comment]
* The apk isnt replaced yet but gna do it
* And yeah :)

**Comment by Martinvlba** [comment]
gonna notify when apk is replaced

**Comment by Martinvlba** [comment]
* apk has been updated to versioncode 38 (Under the releases)

**Comment by IzzySoft** [comment]
Superb! Right in time for today's sync. Will show up in the repo in about 1.5h :smiley:

**Comment by Martinvlba** [comment]
my computer goes biip boop biip boop its brokei

**Comment by IzzySoft** [comment]
Ouch! By the sound of it, it's the spinning disk I'd say. Hope you got good backups!

**Comment by Martinvlba** [comment]
Sry left my github open so my brother messed here

**Comment by IzzySoft** [comment]
Best wishes to him, though. Feel free to remove my (now orphaned) comments connected to his (now removed) comment.
