### ISSUE TITLE
A wonderful application. I installed alpine linux on it and it is running very much. I just want to make a second copy of the application. Is it possible

### ISSUE THREAD

**Issue by gowwe** [NeoTerrm/NeoTerm#65]
A wonderful application. I installed alpine linux on it and it is running very much. I just want to make a second copy of the application. Is it possible

**Comment by Martinvlba** [comment]
not so sure as it will start the same session at /data/data/io.neoterm

**Comment by gowwe** [comment]
Can I get the open source apk from neoterm

في الجمعة، ٢١ مايو ٢٠٢١ ٨:٢٧ م Martin Valba ***@***.***> كتب:

**Comment by Martinvlba** [comment]
Bot so sure what you meant?


If you have telegram then you can message me there: https://t.me/hilledkinged
