### ISSUE TITLE
Login program - if selected, auto-install on first start

### ISSUE THREAD

**Issue by licaon-kter** [NeoTerrm/NeoTerm#7]
...so either do this or fix #6

**Comment by imkiva** [comment]
Good idea~

**Comment by imkiva** [comment]
Available in v1.2.6!

**Comment by licaon-kter** [comment]
There is now another issue here with the selection not sticking at first.

Steps:
* Install/clean app data
* Start
* Settings - general - login settings
* Select `zsh`
* See prompt - select install
* Enter Login settings - see `zsh` as selected
* Close all terminals
* Open a new one - see IT'S NOT `zsh`
* Settings - general - login settings
* See `sh` as selected and NOT `zsh`
* Select `zsh` again
* Close all terminals
* Open a new one - now it's ok, it's `zsh`
