### ISSUE TITLE
I can't access the repo.

### ISSUE THREAD

**Issue by VillagerTom** [NeoTerrm/NeoTerm#74]
Did you accidently remove the neoterm repo from http://neoterm.imkiva.com ? I can access the website, but the directory "neoterm" is missing.

**Comment by Martinvlba** [comment]
Its beacause new repo is hosted here: https://github.com/NeoTerm/NeoTerm-repo

**Comment by LMYMMD** [comment]
It's time to update the wiki pages!  : )

**Comment by VillagerTom** [comment]
Σ( ° △ °|||)︴
![Screenshot_2021-10-23-18-43-52-97](https://user-images.githubusercontent.com/89803422/138553603-1e2d075c-9228-46e6-be20-07e72309c074.png)

**Comment by Martinvlba** [comment]
Add [trusted=yes] after deb in sources.list

**Comment by VillagerTom** [comment]
What happend? I can't use apt anymore after upgrading. 
![Screenshot_2021-10-25-15-15-00-27](https://user-images.githubusercontent.com/89803422/138651399-1d4b4396-f15e-439b-997f-6d27f047b932.png)

**Comment by VillagerTom** [comment]
Android 5.1

**Comment by Martinvlba** [comment]
Lowest api level that neoterm packages support are ( Android 7.0 (API level 24) )

* https://github.com/NeoTerm/neoterm-packages/blob/483da8579b189bc4cf41487743065f4c1256976f/scripts/build/termux_step_setup_variables.sh#L6
