### ISSUE TITLE
Play Protect detecting NeoTerm as harmful app

### ISSUE THREAD

**Issue by alfzki** [NeoTerrm/NeoTerm#77]
I used the github version, is this an intended behavior?

**Comment by GJoe2** [comment]
It needs to download and install adittional content over the app, android flags it as a risky behavior

Other similar apps what they do is to bundle with the app itself, they tend to size more.

**Comment by Martinvlba** [comment]
Gonna close this issue as google play tends to flag all similar apps as harmful ( even if they aren't ).
