### ISSUE TITLE
Android 13 strikes again...

### ISSUE THREAD

**Issue by CamsShaft** [NeoTerrm/NeoTerm#82]
Hey man thanks a ton. I just got your terminal and this popped up. I'm sure it's fine, probably just throwing this warning because I got it off here and the play store is jealous and petty like that. I just want to make sure though. Thanks and so far so good!  Also sorry if this is a duplicate!!!

![Screenshot_20231021_185142_Google Play Store](https://github.com/NeoTerrm/NeoTerm/assets/141678661/2d81aa83-2651-420f-a7be-24dd6b496da4)

**Comment by M05QU170** [comment]
I get same message on huawei phone. Maybe for this reason it was deleted on github and izzy

**Comment by Martinvlba** [comment]
Its because default signing keys were used from android studio that are in current apk's
